// src/actions/types.js

export const SEARCH_PLACES_REQUEST = 'SEARCH_PLACES_REQUEST';
export const SEARCH_PLACES_SUCCESS = 'SEARCH_PLACES_SUCCESS';
export const SEARCH_PLACES_FAILURE = 'SEARCH_PLACES_FAILURE';
export const SELECT_PLACE = 'SELECT_PLACE';
export const FETCH_PLACE_DETAILS_REQUEST = 'FETCH_PLACE_DETAILS_REQUEST';
export const FETCH_PLACE_DETAILS_SUCCESS = 'FETCH_PLACE_DETAILS_SUCCESS';
export const FETCH_PLACE_DETAILS_FAILURE = 'FETCH_PLACE_DETAILS_FAILURE';
